on:
  push:
    paths:
      - frontend/**/*.{js,vue,ts,css,html}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd frontend
          npm ci
          npm run build

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/925092156448/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
          service_account: 'github-actions-upload@nush-compute.iam.gserviceaccount.com'

      - id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: './frontend/dist'
          destination: 'ctflib.junron.dev'
          parent: false
